// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
import { resolve } from "path";

// Load .env.local (Next.js convention) so migrate deploy works when DATABASE_URL is there
config({ path: resolve(process.cwd(), ".env.local") });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] || process.env["DATABASE_URL"]?.replace(/\/[^\/]+$/, "/postgres"),
  },
});
