/**
 * GEDCOM Import Utility
 *
 * Takes an EnrichedDocument (from ligneous-gedcom-lib-api) and writes all
 * data into the database inside a single Prisma transaction.
 *
 * The EnrichedDocument uses:
 *   - UUID .id fields on every entity (generated by ?generateIds=true)
 *   - Slice indexes for FK cross-references (e.g. birth_date_index -> dates[i])
 *   - XREFs for relationship references (e.g. spouse.individual_xref)
 */

import { prisma } from '@/lib/database/prisma';
import { randomUUID } from 'crypto';
import {
  buildXrefMap,
  safeId,
  findByIndex,
  mapDateType,
  mapSex,
  insertJunction,
} from './import-helpers';

/**
 * Import an enriched GEDCOM document into the database.
 *
 * @param {object} enriched  - The enriched document from the lib-api
 * @param {object} stats     - The stats object from the lib-api
 * @param {object} opts      - Import options
 * @param {string} opts.name - Display name for the file/tree
 * @param {string} opts.originalFilename - Original uploaded filename
 * @param {number} [opts.fileSize] - File size in bytes
 * @returns {Promise<{gedcomFile: object, fileId: string}>}
 */
export async function importEnrichedDocument(enriched, stats, opts) {
  const fileId = `f_${randomUUID().replace(/-/g, '').slice(0, 16)}`;
  const fileUuid = randomUUID();

  // Top-level EnrichedDocument fields are PascalCase (Go default serialization),
  // but inner struct fields use snake_case (from Go json tags).
  const dates = enriched.Dates || [];
  const places = enriched.Places || [];
  const surnames = enriched.Surnames || [];
  const givenNames = enriched.GivenNames || [];
  const events = enriched.Events || [];
  const notes = enriched.Notes || [];
  const sources = enriched.Sources || [];
  const repositories = enriched.Repositories || [];
  const media = enriched.Media || [];
  const individuals = enriched.Individuals || [];
  const families = enriched.Families || [];

  const dateIds = dates.map((d) => d.id);
  const placeIds = places.map((p) => p.id);
  const surnameIds = surnames.map((s) => s.id);
  const givenNameIds = givenNames.map((g) => g.id);
  const eventIds = events.map((e) => e.id);
  const noteIds = notes.map((n) => n.id);
  const sourceIds = sources.map((s) => s.id);
  const repoIds = repositories.map((r) => r.id);
  const mediaIds = media.map((m) => m.id);

  const indiXrefToUUID = buildXrefMap(individuals);
  const famXrefToUUID = buildXrefMap(families);

  function resolveDateId(index) {
    return index >= 0 && index < dateIds.length ? dateIds[index] : null;
  }
  function resolvePlaceId(index) {
    return index >= 0 && index < placeIds.length ? placeIds[index] : null;
  }

  const gedcomFile = await prisma.$transaction(async (tx) => {
    // 1. Create GedcomFile record
    const gf = await tx.gedcomFile.create({
      data: {
        id: fileUuid,
        fileId,
        name: opts.name || 'Untitled',
        originalFilename: opts.originalFilename || null,
        individualsCount: stats.individuals || 0,
        familiesCount: stats.families || 0,
        placesCount: stats.places || 0,
        datesCount: stats.dates || 0,
        eventsCount: stats.events || 0,
        notesCount: stats.notes || 0,
        sourcesCount: stats.sources || 0,
        fileSize: opts.fileSize ? BigInt(opts.fileSize) : null,
        status: 'ready',
        parseErrors: 0,
        parseWarnings: 0,
        parsedAt: new Date(),
      },
    });

    // 2. Insert lookup tables
    await insertLookupTables(tx, fileUuid, { dates, places, surnames, givenNames });

    // 3. Insert core entities
    await insertCoreEntities(tx, fileUuid, {
      individuals, families, events, notes, sources, repositories, media,
      dates, places, indiXrefToUUID, resolveDateId, resolvePlaceId,
    });

    // 4. Insert all junction tables
    await insertJunctions(tx, fileUuid, enriched, {
      indiXrefToUUID, famXrefToUUID,
      eventIds, noteIds, sourceIds, surnameIds, givenNameIds, mediaIds, repoIds,
    });

    // 5. Insert relationship edges
    const parentChild = enriched.ParentChild || [];
    const familyChildren = enriched.FamilyChildren || [];
    const spouseEdges = enriched.Spouses || [];

    await insertRelationshipEdges(tx, fileUuid, {
      parentChild, familyChildren, spouseEdges,
      indiXrefToUUID, famXrefToUUID,
    });

    // 6. Update individual flags (has_parents, has_children, has_spouse)
    await updateIndividualFlags(tx, parentChild, spouseEdges, indiXrefToUUID);

    // 7. Build XREF router table
    await buildFileObjectTable(tx, fileUuid, {
      individuals, families, sources, notes, repositories, media,
    });

    return gf;
  }, {
    timeout: 120000,
  });

  return { gedcomFile, fileId };
}

// ---------------------------------------------------------------------------
// Lookup tables (dates, places, surnames, given names)
// ---------------------------------------------------------------------------

async function insertLookupTables(tx, fileUuid, { dates, places, surnames, givenNames }) {
  if (dates.length) {
    await tx.gedcomDate.createMany({
      data: dates.map((d) => ({
        id: d.id,
        fileUuid,
        original: d.original || null,
        dateType: mapDateType(d.type),
        calendar: d.calendar || 'GREGORIAN',
        year: d.year || null,
        month: d.month || null,
        day: d.day || null,
        endYear: d.end_year || null,
        endMonth: d.end_month || null,
        endDay: d.end_day || null,
        hash: d.hash,
      })),
    });
  }

  if (places.length) {
    await tx.gedcomPlace.createMany({
      data: places.map((p) => ({
        id: p.id,
        fileUuid,
        original: p.original,
        name: p.name || null,
        county: p.county || null,
        state: p.state || null,
        country: p.country || null,
        latitude: p.latitude || null,
        longitude: p.longitude || null,
        hash: p.hash,
      })),
    });
  }

  if (surnames.length) {
    await tx.gedcomSurname.createMany({
      data: surnames.map((s) => ({
        id: s.id,
        fileUuid,
        surname: s.value,
        surnameLower: s.lower,
        frequency: s.frequency || 0,
      })),
    });
  }

  if (givenNames.length) {
    await tx.gedcomGivenName.createMany({
      data: givenNames.map((g) => ({
        id: g.id,
        fileUuid,
        givenName: g.value,
        givenNameLower: g.lower,
        frequency: g.frequency || 0,
      })),
    });
  }
}

// ---------------------------------------------------------------------------
// Core entities (individuals, families, events, notes, sources, repos, media)
// ---------------------------------------------------------------------------

async function insertCoreEntities(tx, fileUuid, ctx) {
  const {
    individuals, families, events, notes, sources, repositories, media,
    dates, places, indiXrefToUUID, resolveDateId, resolvePlaceId,
  } = ctx;

  if (individuals.length) {
    await tx.gedcomIndividual.createMany({
      data: individuals.map((ind) => {
        const birthDateId = resolveDateId(ind.birth_date_index);
        const birthPlaceId = resolvePlaceId(ind.birth_place_index);
        const deathDateId = resolveDateId(ind.death_date_index);
        const deathPlaceId = resolvePlaceId(ind.death_place_index);

        const birthDate = birthDateId ? findByIndex(dates, ind.birth_date_index) : null;
        const birthPlace = birthPlaceId ? findByIndex(places, ind.birth_place_index) : null;
        const deathDate = deathDateId ? findByIndex(dates, ind.death_date_index) : null;
        const deathPlace = deathPlaceId ? findByIndex(places, ind.death_place_index) : null;

        return {
          id: ind.id,
          fileUuid,
          xref: ind.xref,
          fullName: ind.full_name || null,
          fullNameLower: ind.full_name_lower || null,
          sex: mapSex(ind.sex),
          birthDateId,
          birthPlaceId,
          birthDateDisplay: birthDate?.original || null,
          birthPlaceDisplay: birthPlace?.original || null,
          birthYear: birthDate?.year || null,
          deathDateId,
          deathPlaceId,
          deathDateDisplay: deathDate?.original || null,
          deathPlaceDisplay: deathPlace?.original || null,
          deathYear: deathDate?.year || null,
          isLiving: !deathDateId,
        };
      }),
    });
  }

  if (families.length) {
    await tx.gedcomFamily.createMany({
      data: families.map((fam) => {
        const marriageDateId = resolveDateId(fam.marriage_date_index);
        const marriagePlaceId = resolvePlaceId(fam.marriage_place_index);
        const marriageDate = marriageDateId ? findByIndex(dates, fam.marriage_date_index) : null;
        const marriagePlace = marriagePlaceId ? findByIndex(places, fam.marriage_place_index) : null;

        return {
          id: fam.id,
          fileUuid,
          xref: fam.xref,
          husbandId: fam.husband_xref ? indiXrefToUUID[fam.husband_xref] || null : null,
          wifeId: fam.wife_xref ? indiXrefToUUID[fam.wife_xref] || null : null,
          husbandXref: fam.husband_xref || null,
          wifeXref: fam.wife_xref || null,
          marriageDateId,
          marriagePlaceId,
          marriageDateDisplay: marriageDate?.original || null,
          marriagePlaceDisplay: marriagePlace?.original || null,
          marriageYear: marriageDate?.year || null,
          childrenCount: fam.children_count || 0,
        };
      }),
    });
  }

  if (events.length) {
    await tx.gedcomEvent.createMany({
      data: events.map((evt) => ({
        id: evt.id,
        fileUuid,
        eventType: evt.event_type,
        customType: evt.custom_type || null,
        dateId: resolveDateId(evt.date_index),
        placeId: resolvePlaceId(evt.place_index),
        value: evt.value || null,
        cause: evt.cause || null,
        agency: evt.agency || null,
        sortOrder: evt.sort_order || 0,
      })),
    });
  }

  if (notes.length) {
    await tx.gedcomNote.createMany({
      data: notes.map((n) => ({
        id: n.id,
        fileUuid,
        xref: n.xref || null,
        content: n.content,
        isTopLevel: n.is_top_level || false,
      })),
    });
  }

  if (sources.length) {
    await tx.gedcomSource.createMany({
      data: sources.map((s) => ({
        id: s.id,
        fileUuid,
        xref: s.xref,
        title: s.title || null,
        author: s.author || null,
        abbreviation: s.abbreviation || null,
        publication: s.publication || null,
        text: s.text || null,
        repositoryXref: s.repository_xref || null,
        callNumber: s.call_number || null,
      })),
    });
  }

  if (repositories.length) {
    await tx.gedcomRepository.createMany({
      data: repositories.map((r) => ({
        id: r.id,
        fileUuid,
        xref: r.xref,
        name: r.name || null,
        address: r.address || null,
        city: r.city || null,
        state: r.state || null,
        country: r.country || null,
        phone: r.phone || null,
        email: r.email || null,
        website: r.website || null,
      })),
    });
  }

  if (media.length) {
    await tx.gedcomMedia.createMany({
      data: media.map((m) => ({
        id: m.id,
        fileUuid,
        xref: m.xref || null,
        fileRef: m.file || null,
        form: m.form || null,
        title: m.title || null,
      })),
    });
  }
}

// ---------------------------------------------------------------------------
// Junction tables (events, notes, sources, names, media, repositories)
// ---------------------------------------------------------------------------

async function insertJunctions(tx, fileUuid, enriched, ids) {
  const {
    indiXrefToUUID, famXrefToUUID,
    eventIds, noteIds, sourceIds, surnameIds, givenNameIds, mediaIds, repoIds,
  } = ids;

  // Events
  await insertJunction(
    tx, tx.gedcomIndividualEvent, enriched.IndividualEvents || [],
    (ie) => indiXrefToUUID[ie.individual_xref] && safeId(eventIds, ie.event_index),
    (ie) => ({ fileUuid, individualId: indiXrefToUUID[ie.individual_xref], eventId: eventIds[ie.event_index], role: ie.role || 'principal' }),
  );
  await insertJunction(
    tx, tx.gedcomFamilyEvent, enriched.FamilyEvents || [],
    (fe) => famXrefToUUID[fe.family_xref] && safeId(eventIds, fe.event_index),
    (fe) => ({ fileUuid, familyId: famXrefToUUID[fe.family_xref], eventId: eventIds[fe.event_index] }),
  );

  // Notes
  await insertJunction(
    tx, tx.gedcomIndividualNote, enriched.IndividualNotes || [],
    (n) => indiXrefToUUID[n.individual_xref] && safeId(noteIds, n.note_index),
    (n) => ({ fileUuid, individualId: indiXrefToUUID[n.individual_xref], noteId: noteIds[n.note_index] }),
  );
  await insertJunction(
    tx, tx.gedcomFamilyNote, enriched.FamilyNotes || [],
    (n) => famXrefToUUID[n.family_xref] && safeId(noteIds, n.note_index),
    (n) => ({ fileUuid, familyId: famXrefToUUID[n.family_xref], noteId: noteIds[n.note_index] }),
  );
  await insertJunction(
    tx, tx.gedcomEventNote, enriched.EventNotes || [],
    (n) => safeId(eventIds, n.event_index) && safeId(noteIds, n.note_index),
    (n) => ({ fileUuid, eventId: eventIds[n.event_index], noteId: noteIds[n.note_index] }),
  );
  await insertJunction(
    tx, tx.gedcomSourceNote, enriched.SourceNotes || [],
    (n) => safeId(sourceIds, n.source_index) && safeId(noteIds, n.note_index),
    (n) => ({ fileUuid, sourceId: sourceIds[n.source_index], noteId: noteIds[n.note_index] }),
  );

  // Sources
  await insertJunction(
    tx, tx.gedcomIndividualSource, enriched.IndividualSources || [],
    (s) => indiXrefToUUID[s.individual_xref] && safeId(sourceIds, s.source_index),
    (s) => ({ fileUuid, individualId: indiXrefToUUID[s.individual_xref], sourceId: sourceIds[s.source_index], page: s.page || null, quality: s.quality || null, citationText: s.citation_text || null }),
  );
  await insertJunction(
    tx, tx.gedcomFamilySource, enriched.FamilySources || [],
    (s) => famXrefToUUID[s.family_xref] && safeId(sourceIds, s.source_index),
    (s) => ({ fileUuid, familyId: famXrefToUUID[s.family_xref], sourceId: sourceIds[s.source_index], page: s.page || null, quality: s.quality || null, citationText: s.citation_text || null }),
  );
  await insertJunction(
    tx, tx.gedcomEventSource, enriched.EventSources || [],
    (s) => safeId(eventIds, s.event_index) && safeId(sourceIds, s.source_index),
    (s) => ({ fileUuid, eventId: eventIds[s.event_index], sourceId: sourceIds[s.source_index], page: s.page || null, quality: s.quality || null, citationText: s.citation_text || null }),
  );

  // Names
  await insertJunction(
    tx, tx.gedcomIndividualSurname, enriched.IndividualSurnames || [],
    (s) => indiXrefToUUID[s.individual_xref] && safeId(surnameIds, s.surname_index),
    (s) => ({ fileUuid, individualId: indiXrefToUUID[s.individual_xref], surnameId: surnameIds[s.surname_index], nameType: s.name_type || 'birth', isPrimary: s.is_primary || false }),
  );
  await insertJunction(
    tx, tx.gedcomIndividualGivenName, enriched.IndividualGivenNames || [],
    (g) => indiXrefToUUID[g.individual_xref] && safeId(givenNameIds, g.given_name_index),
    (g) => ({ fileUuid, individualId: indiXrefToUUID[g.individual_xref], givenNameId: givenNameIds[g.given_name_index], position: g.position || 1, isPrimary: g.is_primary || false }),
  );
  await insertJunction(
    tx, tx.gedcomFamilySurname, enriched.FamilySurnames || [],
    (s) => famXrefToUUID[s.family_xref] && safeId(surnameIds, s.surname_index),
    (s) => ({ fileUuid, familyId: famXrefToUUID[s.family_xref], surnameId: surnameIds[s.surname_index], isPrimary: s.is_primary || false }),
  );

  // Media
  await insertJunction(
    tx, tx.gedcomIndividualMedia, enriched.IndividualMedia || [],
    (m) => indiXrefToUUID[m.individual_xref] && safeId(mediaIds, m.media_index),
    (m) => ({ fileUuid, individualId: indiXrefToUUID[m.individual_xref], mediaId: mediaIds[m.media_index] }),
  );
  await insertJunction(
    tx, tx.gedcomFamilyMedia, enriched.FamilyMedia || [],
    (m) => famXrefToUUID[m.family_xref] && safeId(mediaIds, m.media_index),
    (m) => ({ fileUuid, familyId: famXrefToUUID[m.family_xref], mediaId: mediaIds[m.media_index] }),
  );
  await insertJunction(
    tx, tx.gedcomSourceMedia, enriched.SourceMedia || [],
    (m) => safeId(sourceIds, m.source_index) && safeId(mediaIds, m.media_index),
    (m) => ({ fileUuid, sourceId: sourceIds[m.source_index], mediaId: mediaIds[m.media_index] }),
  );

  // Repositories
  await insertJunction(
    tx, tx.gedcomSourceRepository, enriched.SourceRepositories || [],
    (r) => safeId(sourceIds, r.source_index) && safeId(repoIds, r.repository_index),
    (r) => ({ fileUuid, sourceId: sourceIds[r.source_index], repositoryId: repoIds[r.repository_index], callNumber: r.call_number || null }),
  );
}

// ---------------------------------------------------------------------------
// Relationship edges (parent-child, family-children, spouses)
// ---------------------------------------------------------------------------

async function insertRelationshipEdges(tx, fileUuid, ctx) {
  const { parentChild, familyChildren, spouseEdges, indiXrefToUUID, famXrefToUUID } = ctx;

  await insertJunction(
    tx, tx.gedcomParentChild, parentChild,
    (pc) => indiXrefToUUID[pc.parent_xref] && indiXrefToUUID[pc.child_xref],
    (pc) => ({
      fileUuid,
      parentId: indiXrefToUUID[pc.parent_xref],
      childId: indiXrefToUUID[pc.child_xref],
      familyId: pc.family_xref ? famXrefToUUID[pc.family_xref] || null : null,
      parentType: pc.parent_type || null,
      relationshipType: pc.relationship_type || 'biological',
      pedigree: pc.pedigree || null,
    }),
  );

  await insertJunction(
    tx, tx.gedcomFamilyChild, familyChildren,
    (fc) => famXrefToUUID[fc.family_xref] && indiXrefToUUID[fc.child_xref],
    (fc) => ({
      fileUuid,
      familyId: famXrefToUUID[fc.family_xref],
      childId: indiXrefToUUID[fc.child_xref],
      childXref: fc.child_xref || null,
      birthOrder: fc.birth_order || null,
    }),
  );

  await insertJunction(
    tx, tx.gedcomSpouse, spouseEdges,
    (sp) => indiXrefToUUID[sp.individual_xref] && indiXrefToUUID[sp.spouse_xref],
    (sp) => ({
      fileUuid,
      individualId: indiXrefToUUID[sp.individual_xref],
      spouseId: indiXrefToUUID[sp.spouse_xref],
      familyId: sp.family_xref ? famXrefToUUID[sp.family_xref] || null : null,
    }),
  );
}

// ---------------------------------------------------------------------------
// Flag updates (hasParents, hasChildren, hasSpouse)
// ---------------------------------------------------------------------------

async function updateIndividualFlags(tx, parentChild, spouseEdges, indiXrefToUUID) {
  const childXrefs = new Set(parentChild.map((pc) => pc.child_xref));
  const parentXrefs = new Set(parentChild.map((pc) => pc.parent_xref));
  const spouseXrefs = new Set(spouseEdges.flatMap((sp) => [sp.individual_xref, sp.spouse_xref]));

  for (const xref of childXrefs) {
    if (indiXrefToUUID[xref]) {
      await tx.gedcomIndividual.update({
        where: { id: indiXrefToUUID[xref] },
        data: { hasParents: true },
      });
    }
  }
  for (const xref of parentXrefs) {
    if (indiXrefToUUID[xref]) {
      await tx.gedcomIndividual.update({
        where: { id: indiXrefToUUID[xref] },
        data: { hasChildren: true },
      });
    }
  }
  for (const xref of spouseXrefs) {
    if (indiXrefToUUID[xref]) {
      await tx.gedcomIndividual.update({
        where: { id: indiXrefToUUID[xref] },
        data: { hasSpouse: true },
      });
    }
  }
}

// ---------------------------------------------------------------------------
// XREF router table (GedcomFileObject)
// ---------------------------------------------------------------------------

async function buildFileObjectTable(tx, fileUuid, ctx) {
  const { individuals, families, sources, notes, repositories, media } = ctx;
  const fileObjects = [];

  for (const ind of individuals) {
    fileObjects.push({ fileUuid, xref: ind.xref, objectType: 'INDI', objectUuid: ind.id });
  }
  for (const fam of families) {
    fileObjects.push({ fileUuid, xref: fam.xref, objectType: 'FAM', objectUuid: fam.id });
  }
  for (const src of sources) {
    fileObjects.push({ fileUuid, xref: src.xref, objectType: 'SOUR', objectUuid: src.id });
  }
  for (const n of notes.filter((n) => n.xref)) {
    fileObjects.push({ fileUuid, xref: n.xref, objectType: 'NOTE', objectUuid: n.id });
  }
  for (const repo of repositories) {
    fileObjects.push({ fileUuid, xref: repo.xref, objectType: 'REPO', objectUuid: repo.id });
  }
  for (const m of media.filter((m) => m.xref)) {
    fileObjects.push({ fileUuid, xref: m.xref, objectType: 'OBJE', objectUuid: m.id });
  }

  if (fileObjects.length) {
    await tx.gedcomFileObject.createMany({ data: fileObjects });
  }
}
